import assert from "node:assert/strict";
import { access, cp, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { temporaryDirectory } from "../test-support/helpers.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const plugin = path.join(root, "integrations", "codex", "qarinah");
const claudePlugin = path.join(root, "integrations", "claude", "qarinah");

test("repository marketplaces reference only the reviewed local plugin packages", async () => {
  const codexMarketplace = JSON.parse(await readFile(path.join(root, ".agents", "plugins", "marketplace.json"), "utf8"));
  assert.equal(codexMarketplace.name, "qarinah");
  assert.deepEqual(codexMarketplace.plugins.map(({ name, source }) => ({ name, source })), [{
    name: "qarinah",
    source: { source: "local", path: "./integrations/codex/qarinah" }
  }]);
  await access(path.join(root, codexMarketplace.plugins[0].source.path, ".codex-plugin", "plugin.json"));

  const claudeMarketplace = JSON.parse(await readFile(path.join(root, ".claude-plugin", "marketplace.json"), "utf8"));
  assert.equal(claudeMarketplace.name, "qarinah");
  assert.deepEqual(claudeMarketplace.plugins.map(({ name, source }) => ({ name, source })), [{
    name: "qarinah",
    source: "./integrations/claude/qarinah"
  }]);
  await access(path.join(root, claudeMarketplace.plugins[0].source, ".claude-plugin", "plugin.json"));
});

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    import("node:child_process").then(({ spawn }) => {
      const child = spawn(command, args, {
        cwd: options.cwd,
        env: options.env || process.env,
        shell: false,
        windowsVerbatimArguments: options.windowsVerbatimArguments === true,
        stdio: ["pipe", "pipe", "pipe"]
      });
      let stdout = "";
      let stderr = "";
      child.stdout.setEncoding("utf8");
      child.stderr.setEncoding("utf8");
      child.stdout.on("data", (chunk) => { stdout += chunk; });
      child.stderr.on("data", (chunk) => { stderr += chunk; });
      child.on("error", reject);
      child.on("close", (code, signal) => resolve({ code, signal, stdout, stderr }));
      child.stdin.end(options.input || "");
    }, reject);
  });
}

function assertSucceeded(result) {
  assert.equal(result.signal, null, result.stderr);
  assert.equal(result.code, 0, result.stderr);
}

test("Codex plugin declares every supported lifecycle hook", async () => {
  const hooks = JSON.parse(await readFile(path.join(plugin, "hooks", "hooks.json"), "utf8"));
  assert.deepEqual(Object.keys(hooks.hooks).sort(), [
    "PermissionRequest", "PostCompact", "PostToolUse", "PreCompact", "PreToolUse", "SessionStart", "Stop",
    "SubagentStart", "SubagentStop", "UserPromptSubmit"
  ]);
  for (const groups of Object.values(hooks.hooks)) {
    for (const group of groups) {
      for (const hook of group.hooks) {
        assert.equal(hook.type, "command");
        assert.match(hook.command, /^node "\$PLUGIN_ROOT\/runtime\/qarinah\.mjs" hook codex --quiet$/);
        assert.match(hook.commandWindows, /^node "%PLUGIN_ROOT%\\runtime\\qarinah\.mjs" hook codex --quiet$/);
        assert.doesNotMatch(`${hook.command}\n${hook.commandWindows}`, /scripts|\.cmd|npx/);
      }
    }
  }
});

test("plugin package contains a synchronized self-contained runtime", async () => {
  const manifest = JSON.parse(await readFile(path.join(plugin, ".codex-plugin", "plugin.json"), "utf8"));
  const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
  assert.equal(manifest.name, "qarinah");
  assert.equal(manifest.version, packageJson.version);
  await access(path.join(plugin, "skills", "qarinah-context", "SKILL.md"));
  const runtime = await readFile(path.join(plugin, "runtime", "qarinah.mjs"), "utf8");
  assert.match(runtime, /GENERATED by scripts\/build-plugins\.mjs/);
  assert.doesNotMatch(runtime, /node:child_process|qarinah\.cmd|spawn\(/);
  const mcp = JSON.parse(await readFile(path.join(plugin, ".mcp.json"), "utf8"));
  assert.deepEqual(mcp.mcpServers.context.args, ["./runtime/qarinah.mjs", "mcp"]);
});

test("Claude Code plugin uses portable exec hooks and a bundled read-only MCP server", async () => {
  const manifest = JSON.parse(await readFile(path.join(claudePlugin, ".claude-plugin", "plugin.json"), "utf8"));
  const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
  assert.equal(manifest.name, "qarinah");
  assert.equal(manifest.version, packageJson.version);
  assert.equal(Object.hasOwn(manifest, "openaiCapabilities"), false);
  assert.equal(manifest.hooks, "./hooks/hooks.json");
  assert.equal(manifest.mcpServers, "./.mcp.json");
  const hooks = JSON.parse(await readFile(path.join(claudePlugin, "hooks", "hooks.json"), "utf8"));
  assert.deepEqual(Object.keys(hooks.hooks).sort(), [
    "PermissionDenied", "PostCompact", "PostToolUse", "PostToolUseFailure", "PreCompact", "PreToolUse",
    "SessionEnd", "SessionStart", "Stop", "StopFailure", "SubagentStart", "SubagentStop", "UserPromptSubmit"
  ]);
  for (const groups of Object.values(hooks.hooks)) {
    for (const group of groups) {
      for (const hook of group.hooks) {
        assert.equal(hook.type, "command");
        assert.equal(hook.command, "node");
        assert.deepEqual(hook.args, ["${CLAUDE_PLUGIN_ROOT}/runtime/qarinah.mjs", "hook", "claude", "--quiet"]);
      }
    }
  }
  const mcp = JSON.parse(await readFile(path.join(claudePlugin, ".mcp.json"), "utf8"));
  assert.deepEqual(mcp.mcpServers.context.args, ["${CLAUDE_PLUGIN_ROOT}/runtime/qarinah.mjs", "mcp"]);
  await access(path.join(claudePlugin, "skills", "qarinah-context", "SKILL.md"));
  const runtime = await readFile(path.join(claudePlugin, "runtime", "qarinah.mjs"), "utf8");
  assert.match(runtime, /GENERATED by scripts\/build-plugins\.mjs/);
  assert.doesNotMatch(runtime, /node:child_process|qarinah\.cmd|spawn\(/);
});

test("copied standalone plugin captures with no parent package or PATH fallback", async (t) => {
  const sandbox = await temporaryDirectory(t);
  const copiedPlugin = path.join(sandbox, "standalone Qarinah ü plugin");
  const workspace = path.join(sandbox, "consumer workspace");
  const maliciousPath = path.join(sandbox, "malicious-path");
  const marker = path.join(sandbox, "path-fallback-ran.txt");
  await cp(plugin, copiedPlugin, { recursive: true });
  await import("node:fs/promises").then(({ mkdir }) => mkdir(maliciousPath, { recursive: true }));
  await writeFile(path.join(maliciousPath, "qarinah.cmd"), `@echo compromised>"${marker}"\r\n`, "utf8");
  await writeFile(path.join(maliciousPath, "qarinah"), `#!/bin/sh\nprintf compromised > '${marker.replaceAll("'", "'\\''")}'\n`, { encoding: "utf8", mode: 0o700 });

  const runtime = path.join(copiedPlugin, "runtime", "qarinah.mjs");
  const env = {
    ...process.env,
    PATH: `${maliciousPath}${path.delimiter}${process.env.PATH || ""}`
  };
  const initialized = await run(process.execPath, [runtime, "init", workspace], { cwd: sandbox, env });
  assertSucceeded(initialized);

  const hookInput = JSON.stringify({
    cwd: workspace,
    hook_event_name: "PostToolUse",
    model: "gpt-5.6-sol",
    permission_mode: "default",
    session_id: "standalone-session",
    tool_input: { command: "npm test", authorization: "Bearer top-secret-token" },
    tool_name: "Bash",
    tool_response: { exit_code: 0, output: "passed" },
    tool_use_id: "standalone-tool",
    transcript_path: null,
    turn_id: "standalone-turn"
  });
  const quiet = await run(process.execPath, [runtime, "hook", "codex", "--quiet"], { cwd: workspace, env, input: hookInput });
  assertSucceeded(quiet);
  assert.equal(quiet.stdout, "");

  const hooks = JSON.parse(await readFile(path.join(copiedPlugin, "hooks", "hooks.json"), "utf8"));
  const command = hooks.hooks.PostToolUse[0].hooks[0];
  const hookEnv = { ...env, PLUGIN_ROOT: copiedPlugin };
  const throughShell = process.platform === "win32"
    ? await run("cmd.exe", ["/d", "/s", "/c", command.commandWindows], { cwd: workspace, env: hookEnv, input: hookInput, windowsVerbatimArguments: true })
    : await run("/bin/sh", ["-c", command.command], { cwd: workspace, env: hookEnv, input: hookInput });
  assertSucceeded(throughShell);
  assert.equal(throughShell.stdout, "");

  assertSucceeded(await run(process.execPath, [runtime, "build"], { cwd: workspace, env }));
  const doctor = await run(process.execPath, [runtime, "doctor"], { cwd: workspace, env });
  assertSucceeded(doctor);
  assert.equal(JSON.parse(doctor.stdout).ok, true);
  const ledger = await readFile(path.join(workspace, ".qarinah", "events", "events.jsonl"), "utf8");
  assert.equal(ledger.includes("top-secret-token"), false);
  await assert.rejects(() => access(marker));
});
