import assert from "node:assert/strict";
import { copyFile, mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(path.join(repositoryRoot, "package.json"), "utf8"));
const versionSource = await readFile(path.join(repositoryRoot, "src", "version.js"), "utf8");
assert.match(versionSource, new RegExp(`QARINAH_VERSION\\s*=\\s*[\"']${packageJson.version.replaceAll(".", "\\.")}[\"']`), "Runtime and package versions must match.");

const plugins = [
  {
    name: "Codex",
    root: path.join(repositoryRoot, "integrations", "codex", "qarinah"),
    manifest: path.join(".codex-plugin", "plugin.json")
  },
  {
    name: "Claude Code",
    root: path.join(repositoryRoot, "integrations", "claude", "qarinah"),
    manifest: path.join(".claude-plugin", "plugin.json")
  }
];

const checking = process.argv.includes("--check");
const temporaryDirectory = checking ? await mkdtemp(path.join(os.tmpdir(), "qarinah-plugin-build-")) : null;

try {
  for (const plugin of plugins) {
    const manifest = JSON.parse(await readFile(path.join(plugin.root, plugin.manifest), "utf8"));
    assert.equal(manifest.version, packageJson.version, `${plugin.name} plugin and package versions must match.`);
    const outputFile = checking
      ? path.join(temporaryDirectory, `${plugin.name.toLowerCase().replaceAll(" ", "-")}-qarinah.mjs`)
      : path.join(plugin.root, "runtime", "qarinah.mjs");
    const result = await build({
      entryPoints: [path.join(repositoryRoot, "bin", "qarinah.js")],
      outfile: outputFile,
      bundle: true,
      platform: "node",
      format: "esm",
      target: "node22",
      sourcemap: false,
      minify: false,
      legalComments: "inline",
      metafile: true,
      banner: { js: `// GENERATED by scripts/build-plugins.mjs for Qarinah ${packageJson.version}. DO NOT EDIT.` },
      logLevel: "silent"
    });
    const unsafeExternal = Object.values(result.metafile.outputs)
      .flatMap((output) => output.imports)
      .filter((entry) => entry.external)
      .map((entry) => entry.path)
      .filter((specifier) => !specifier.startsWith("node:"));
    assert.deepEqual(unsafeExternal, [], `${plugin.name} bundle has non-Node external imports: ${unsafeExternal.join(", ")}`);
    const generated = await readFile(outputFile);
    assert.equal(generated.includes(Buffer.from(repositoryRoot)), false, `${plugin.name} bundle contains an absolute repository path.`);
    if (checking) {
      const committed = await readFile(path.join(plugin.root, "runtime", "qarinah.mjs"));
      assert.ok(
        generated.equals(committed),
        `Committed ${plugin.name} plugin runtime is stale. Run \`npm run build:plugins\`.`
      );
    } else {
      process.stdout.write(`Built ${path.relative(repositoryRoot, outputFile)}\n`);
    }
    for (const legalFile of ["LICENSE", "THIRD_PARTY_NOTICES.md"]) {
      const source = path.join(repositoryRoot, legalFile);
      const target = path.join(plugin.root, legalFile);
      if (checking) {
        const [expected, committed] = await Promise.all([readFile(source), readFile(target)]);
        assert.ok(expected.equals(committed), `${plugin.name} ${legalFile} is stale. Run \`npm run build:plugins\`.`);
      } else {
        await copyFile(source, target);
      }
    }
  }
  if (checking) process.stdout.write("Codex and Claude Code plugin runtimes are current.\n");
} finally {
  if (temporaryDirectory) await rm(temporaryDirectory, { recursive: true, force: true });
}
